server:
    port: 8090

task:
    name: hamada
    age: 25

logging:
    level:
        com.example.tracker: DEBUG
        org.springframework.security.web.FilterChainProxy: DEBUG


management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics

