server:
    port: 8090

task:
    name: hamada
    age: 25

logging:
    level:
        com.example.tracker: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics